### PR TITLE
One off load of JSON and json check message

### PR DESCRIPTION
**Pull request by superbudvar**

### CODE REVIEW

**Comment by DrakiaXYZ** [comment]
Nice catch, I didn't even notice it was being reloaded every search. I'll try this out when I'm off work tonight.

**Comment by superbudvar** [comment]
It certain speeds up loading and testing the results screen :)
However, I'm somewhat new to c/c++ so I've only globalised the character array. Not sure it's the best approach, but I believe having the load at startup improves the experience

**Comment by llakssz** [comment]
Thanks! This needed a little warning message when it can't find the json file, perfect.
I see 4 lines above where you check if the CIA file exists, isn't it better to just do `cp.c_str()`? instead of the memcpy and stuff? Or is there a reason you did it that way? (I'm not an expert!)
And I didn't realize at all about the json thing, thanks :grapes:

**Comment by DrakiaXYZ** [comment]
Looks like the ciaPath and memcpy aren't really needed, you can just use cp.c_str() (Right now it also contains a memory leak, since ciaPath isn't freed).

sourceData being global isn't really an issue, since it's used multiple times. Much faster than reading it on every search. I personally prefer a delay on load versus a delay on every search.

**Comment by llakssz** [comment]
Ok, thanks for the help!

**Comment by superbudvar** [comment]
hmm, sure I tried the c_str first, but couldn't cast it correctly. The reason I wrote that is mainly as I wasn't sure how to cast a char to std::string as I wanted to re-usee the existing function call

**Comment by llakssz** [comment]
I have difficultly with strings and chars, it's ok!
I wish everything could be in python :snake:

**Pull request merged**
