### PR TITLE
Improve CIA generation speed

### PR DESCRIPTION
**Pull request by DrakiaXYZ**
Had to do a few odd things with this one due to the combination of C and C++ code in the project.
- Convert DownloadFile to C, since we need to access it from cia.c now
- Remove some typedefs that are defined in 3ds.h from types.h (Need 3ds.h in util.c now for download)
- Fixed a few warnings about sprintf's
- Move NUS_URL to a define since we need it in cia.c now
- Remove some debug output I accidentally left in my last PR

### CODE REVIEW

**Comment by DrakiaXYZ** [comment]
This depends on changes in https://github.com/llakssz/CIAngel/pull/11 so make sure to check that one out/merge it first.

**Comment by llakssz** [comment]
I have a feeling this might interfere with my change I'm just about to commit! I'll have a look, I merged yours first because it's more important I think. I can alter mine if needed.
Thanks

**Comment by DrakiaXYZ** [comment]
If you do your work in branches, and do pull requests like this (I believe you can still do PRs against your own trunk), GitHub will let you know if the merge can happen cleanly. And if not, you can do the work to fix the merge issues within the branch which makes things a bit easier :)

**Comment by llakssz** [comment]
Sounds like a good idea! :computer:
I read that the master branch should always be buildable, so it will be nice to submit broken stuff to an experimental branch!

**Pull request merged**
