### PR TITLE
Installer

### PR DESCRIPTION
**Pull request by DrakiaXYZ**
Allow directly installing a CIA instead of having to download first, and install later.
Add progress bar to downloads (If we can get the total filesize)
Output current content # and total content # when downloading/installing
Includes a check that the software isn't designed specifically for a N3DS when installing on an O3DS

This opens a handle to the CIA install destination (Using AM_StartCiaInstall), and downloads directly to this location. The only temp files created are tmd and cetk as normal. This is an alternate to the normal download, and isn't forced. While I've tested this, my wifi sucks (Hotel) and I can't do a full test of multiple CIAs to make sure everything works, so the feature is marked experimental.

svchax is required for CIA installation to work correctly. I've noticed a few crashes on startup (I think it's if I load the eShop before loading CIAngel), not sure if that's related to svchax or not.

### CODE REVIEW

**Comment by llakssz** [comment]
I built it fine, but the 3 or 4 times I tried to load it it crashes. (The keyboard that usually flashes on the top screen for a little bit before going to the bottom screen, stays there at the top)
I'm on an O3DS using10.3 emunand, with GW mode.
I can try on my N3DS using 10.7 emunand with aureinand.

**Comment by DrakiaXYZ** [comment]
That's the behaviour I was running into, but only if I loaded the eShop before loading it. Do you run into crashing issues if you try loading FBI through HBL? (I based the code on theirs)

**Comment by llakssz** [comment]
As a matter of fact, yes when I load FBI through hbl it crashes, I didn't see anything...
That was on my N3DS, I load homebrew from the hbl installed on my home menu. I load homebrew the same way on my O3DS.
So if FBI 2 doesn't run on my N3DS, maybe this won't run either?
I'll read the FBI thread and see if other people are having problems.

**Comment by DrakiaXYZ** [comment]
Bah, that's lame :( Might be svchax instabilities. I read that it's not guaranteed kernel access every time. I figured I could just drop install mode dynamically if it failed, but it appears it's actually killing the console.

Do you have FBI installed as a standalone CIA by any chance? Maybe once I have the CIA building, that could be a workaround for people who run into issues with the 3dsx?

**Comment by llakssz** [comment]
No I don't but once CIA gen is done I can try! I guess FBI will work as a CIA, but yes I need to test.

**Comment by DrakiaXYZ** [comment]
That's kind of a pain. And from my testing I wasn't able to trigger svchax later in the run of the program, it seems it needs to be initialized prior to initializing the AM system. I'll finish up this CIA stuff, and see what I can do about the crashing.

**Comment by llakssz** [comment]
Take your time, especially if you are on holiday.
I'm going to try and add some json support, for reading data. First I have to create the json data to be read, I'll do that in python.

**Comment by DrakiaXYZ** [comment]
Could I get you to give this CIA a try?
https://thedgtl.net/3ds/CIAngel.cia

**Comment by DrakiaXYZ** [comment]
I did some tests, and the CIA definitely works better for install mode, as it doesn't require doing svchax to install CIAs.

One option could be disabling direct install mode while running as a 3dsx, and only having that option when running as an installed CIA?

**Comment by llakssz** [comment]
Sure I'll try that file, thanks.
Yeah I guess that is a possibility, and it will have to be done I guess!
I'll check with Stevevice10 and see if he has any fix for FBI not working, lots more people use that so I reckon he should have made/be working on a fix or something...

**Comment by DrakiaXYZ** [comment]
Yeah, though if it's a limitation of svchax/memchunkhax, I'm not sure how much he can do in the way of a fix.

**Comment by llakssz** [comment]
Ok the CIA works fine... I guess I will have to use this to test, but not a big problem now that you added the latest commit!

**Pull request merged**
