### PR TITLE
Switch the UI to a menu based system

### PR DESCRIPTION
**Pull request by DrakiaXYZ**
Code definitely needs cleaned up at some point, but it works, and should be pretty simple to add new menus in the future for anyone who wants to contribute :)

### CODE REVIEW

**Comment by DrakiaXYZ** [comment]
I did as much testing as I could to make sure I didn't break any features, both 3dsx and CIA versions work, etc. Let me know how it works for you :)

**Comment by Ryuzaki-MrL** [comment]
Wow, amazing job as always!

**Comment by ghost** [comment]
Love it!

**Comment by llakssz** [comment]
I will build and see how things look now! Thanks for the work! :ice_cream:

**Comment by ghost** [comment]
Best commit ever! I tested it out and here's some extra things that I think should be changed:
1. Fix bug where when you're typing, the text flashes
2. Change the color of the blue bar to something that lets the text stand out more - like green
3. Use L or R to change to install mode instead of the menu button
4. When the app is in download mode- use a green bar, and when it is in install, make it red
Thank you again for the awesome commit!

**Pull request merged**
