### PR TITLE
Improve search by using std::string::find

### PR DESCRIPTION
**Pull request by jmazouri**
This makes searching a lot more intuitive by filtering titles that contain the (case-insensitive) search query instead of levenshtein distance (but still uses LD for sorting).

### CODE REVIEW

**Comment by llakssz** [comment]
From what I understand, if I type in 'Pokemon', your code would not show me 'Pokémon'?

The ld is not just for sorting, I wanted it because some characters we are unable to type, so we 'need' this fuzzy/error accepting searching, not just searching for a string inside a string.
But I might be misunderstanding your commit!

**Comment by jmazouri** [comment]
Ah, that makes sense - it didn't occur to me you were using it for that purpose. It may be useful to implement UTF-8 normalization in the future, but for now, I've modified it to simply prioritize titles that contain the search query instead of isolate them (by . 

Through testing, I successfully found both Pokémon games via searching "Pokemon", as well as Street Fighter IV by searching "fighter" and "street".

**Comment by llakssz** [comment]
Ok, I waited for the UI overhaul to merge this, and yes sorry it will need some changes, there are conflicts.
Do I fix this or do you? I'm new to git :)

**Comment by jmazouri** [comment]
I believe to have merged it correctly - I am experiencing some crash bugs, however, I'm not sure if it's due to my code or the new menu code. I will look into it further.

**Comment by llakssz** [comment]
Ok no problem. Good luck fixing, this will be useful!
From my small testing, the new menu didn't crash anything to me, but of course, let us know if you keep crashing somewhere.

**Comment by airkingbr** [comment]
I try the new menu with this code for search, maybe the problem is around games with big names. When i search kirby, all ok... when i search for fighter the problem occur. maybe this help, or not! Thanks for CIAngel.!

**Comment by airkingbr** [comment]
I tested now... and install out run 3d... still crash on exit ciangel. Thx.

**Comment by Paradox355** [comment]
I manually added the code for the string::find in my local copy of the latest master, and it worked like a charm. Where "Fire Emblem" (two words only) previously never returned any Fire Emblem games, now Fire Emblem Awakening and Fire Emblem Shadow Dragon are at the top of the list.

I did change the ld value where string::find returned true. I just changed it to ld = 1 to avoid possibility of reduction to  < 0. Setting value to 1 allows anything returned by the string::find to sort to top of the list. I'll push the code I used to my fork later tonight.

**Comment by llakssz** [comment]
Ok, well github still tells me there are branch conflicts to resolve.
I want this feature to be added :) I manually add the code, I fix the conflict, or @jmazouri fixes it?

**Comment by jmazouri** [comment]
It seems the change is simple enough - I will push a commit to this PR later today.

**Comment by llakssz** [comment]
Good, thanks!

**Comment by llakssz** [comment]
@jmazouri - I'm able to merge it, so I think the conflicts are ok now.
You are finished and want me to merge?

**Comment by jmazouri** [comment]
Unfortunately, it's still crashing on specific searches. I'm not well versed in debugging c++, and I can't quite figure out why. I can't recommend merging until that issue is resolved. 

If anyone would like to assist, searching "Hunter" crashes back to the homescreen every single time. Other queries work as intended.

**Comment by Paradox355** [comment]
I think this is a memory allocation crash; which using string::find can cause. A search of the JSON showed 8 matches for "Hunter". I did some playing around and just about every time the string::find would have returned > 4 results (did have one success with 6), the app crashed.

Before I saw this post about using string::find, I was looking at just splitting the search and temp strings  into words and and doing an ld compare on only the words in search words array. We want to be mindful of ignoring any extra words in the temp array, as that only adds to the total ld count. Then we could perform the < 10 calculation on the sum of the ld returns from the separate search words.

**Comment by llakssz** [comment]
Better search would be great, but if doing the LD for each word instead of each search string - it might actually take like 10 seconds to perform. I'm sure you can notice a delay when searching already. Not that I don't want improvements, I do, but maybe at the expense of waiting 10 seconds for the results it's not worth it... or maybe it is! I don't really use the app, it's for other people.

**Comment by llakssz** [comment]
Ok as of 0.7, we have a nice fuzzy search. I'm closing this. Sorry for any wasted time - thanks for the help.

**Pull request closed without merging**
