### PR TITLE
Trying to change search to be based on uppercase strings

### PR DESCRIPTION
**Pull request by Gummygamer**
Case sensitivity seems unecessary when matching the names, to I think we should compare the uppercase versions of them.

### CODE REVIEW

**Comment by Gummygamer** [comment]
The example that led me to this was searching for "Yokai Watch" when "YO-KAI WATCH" is what is there in json.

**Comment by Gummygamer** [comment]
A little fix was needed to my code.

**Comment by noirscape** [comment]
Whilst I'm not @llakssz , would you mind rebasing the commits to clean up the commit history?

**Comment by llakssz** [comment]
7, 9 commits? :shaved_ice: 
I didn't think about this, thanks though.
@ev1l0rd  - so what can I do, I want to merge this but will it just add 1 commit or all of them?

**Comment by llakssz** [comment]
Ok, I see this only adds like 15 lines.
I have been guilty of it too, committing with some errors etc, but still, please check before you submit a PR.

**Comment by Gummygamer** [comment]
So, should I redo everything to make it clean?

**Comment by DrakiaXYZ** [comment]
It's a little old, but this post may help you with rebasing to a single commit: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

:)

**Comment by Gummygamer** [comment]
Thanks for the feedback. :)

**Comment by Gummygamer** [comment]
I will close this PR because I just opened a new one with 1 commit only.

**Pull request closed without merging**
