### PR TITLE
Menu pagination

### PR DESCRIPTION
**Pull request by superbudvar**
Adapted menus so we can have more results.

There was a file rename, so it looks like there are more changes than there are. The main changes to the menu code can be found in **_titles_multkey_draw_** (new) and  _**menu_multkey_draw**_

There's a bit more info in the commit message for 6b6b3d3

### CODE REVIEW

**Comment by DrakiaXYZ** [comment]
Ah, that's what you were working on. I saw your fork making some pretty big changes to the menu stuff, and was wondering if it was for a PR :)

Going to take a look over this, see if I spot anything that might cause issues. Thanks!

**Comment by DrakiaXYZ** [comment]
Looks good, bit of cleanup that could be done but overall it works great!

**Comment by llakssz** [comment]
Ok, I needed to wait for @TheDgtl to check this out since I didn't touch the menus at all!
Thanks for the work!

**Comment by superbudvar** [comment]
@TheDgtl Yes; I've made a lot of changes, but it's at a bit of a halfway point between using console and gui, and then realised that the merge would have been a nightmare, so I'm drip feeding my "enhancements" in until the merge will be easier. Hopefully I'll have a candidate for consideration soon :)

**Pull request merged**
