### PR TITLE
manual key entry fix; corrected scope of variable 'key'

### PR DESCRIPTION
**Pull request by superbudvar**
fix for #71

### CODE REVIEW

**Comment by DrakiaXYZ** [comment]
While you're in there:
"key" is also defined at the top of the function, which can be deleted (Unused outside the loop)
The "encTitleKey" length check  (In the json lookup for manual entry) is using .size() instead of .length() too, could you update that?

:+1:

**Comment by superbudvar** [comment]
I've removed the string declaration.

Already picked up on the size thing for inconsistency.

I also added the message telling you the entered size (I added it for debugging, but users might like to know where they went wrong)

**Comment by DrakiaXYZ** [comment]
There's still a .size on line 680 https://github.com/superbudvar/CIAngel/blob/ticket-entry-fix/source/main.cpp#L680

Otherwise looks good :+1:

**Comment by llakssz** [comment]
Nice fix!

**Pull request merged**
