### PR TITLE
Added a keyboard

### PR DESCRIPTION
**Pull request by alice157**
This fork has a keyboard added, which allows the user to input keys and ids from their 3ds.

### CODE REVIEW

**Comment by alice157** [comment]
I forgot to change the formatting so it doesn't look awful, and I left some build files in. I don't use github very often so I'm not sure if I can cancel this request, but I'll have a fixed request up pretty soon.

**Comment by DrakiaXYZ** [comment]
If you commit the fixes to the same branch they should show up as part of the pull request as long as it hasn't been accepted yet.

**Comment by DrakiaXYZ** [comment]
You will also want to make sure the generated binary files aren't part of the PR (The .3dsx, .elf, .smdh, and the 'build' directory).

**Comment by alice157** [comment]
Alright, I fixed it. Should be good now.

**Comment by llakssz** [comment]
Incredible and fast! I can't wait to test it!
Thank you.

**Pull request merged**
